version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://electricfanshopserver.database.windows.net:1433;database=ElectricFanShopDB;encrypt=true;trustServerCertificate=false;loginTimeout=30;
      SPRING_DATASOURCE_USERNAME: fanshopadmin
      SPRING_DATASOURCE_PASSWORD: admin@1234
    restart: always
