spring:
  application:
    name: electricfanshop
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ElectricFanShopDBVer2;encrypt=false
    username: sa
    password: 1234
  jpa:
    show-sql: true