spring:
  config:
    import: optional:dotenv:.env

  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}

server:
  port: ${SERVER_PORT}

app:
  oauth2:
    success-redirect-url: ${OAUTH2_SUCCESS_REDIRECT_URL}

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web.client.RestTemplate: DEBUG

